# Generated by Django 3.0.2 on 2020-01-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='hasBeenRead',
            field=models.BooleanField(default=False),
        ),
    ]
