# Generated by Django 2.2 on 2020-02-01 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200201_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='friend',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='friend', to='accounts.Profile'),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='inviter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inviter', to='accounts.Profile'),
        ),
    ]
