# Generated by Django 2.2 on 2020-02-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200201_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='friend_ship',
            field=models.ManyToManyField(through='accounts.FriendShip', to='accounts.Profile'),
        ),
    ]
