# Generated by Django 2.2 on 2020-02-01 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200201_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='friend_ship',
        ),
    ]
