# Generated by Django 2.2 on 2020-02-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='icon',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(default='random_group', max_length=256),
            preserve_default=False,
        ),
    ]
